### ISSUE TITLE
install service issue

### ISSUE THREAD

**Issue by andreae75** [erizet/TopshelfHosting#1]
Hi, nice work, was so easy to add your code to make installation work, but i have some issue.

After use stardard installation:

` dotnet ./MyService.dll install`

i saw that topshelf assume that there is a executable called ./MyService.exe, and when service start, an error appears.

Instead of manually ack the install, do u have any workaround ?

**Comment by erizet** [comment]
Thank you! I think you have to make a console-app that targets .Net Framework. It will produce an exe that you can run. I've updated the sample project. I also updated the lib to target netstandard2.0.
