### ISSUE TITLE
Support for CancellationToken

### ISSUE THREAD

**Issue by RafVandesande** [erizet/TopshelfHosting#2]
Hi Erik,

Thanks for this nice and handy utility!

I have a feature request... I would like the CancellationToken that is passed into the StartAsync and StopAsync methods of the IHostedService to have its IsCancellationRequested property set to true when the service is stopped, so that I can cancel long running jobs and wait for them to finish.
I am more than happy to submit a PR if you like.

**Comment by erizet** [comment]
I'm glad you like it. I think the purpose of the CancellationTokens is to cancel the start/stop processes - not the longrunning service. Have a look here 
https://docs.microsoft.com/sv-se/dotnet/api/microsoft.extensions.hosting.ihostedservice.startasync?view=aspnetcore-2.2#Microsoft_Extensions_Hosting_IHostedService_StartAsync_System_Threading_CancellationToken_ 

and here

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-2.2
